/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M26
 * Generated at: 2017-10-10 18:30:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class portfolio_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\">\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>Portfolio</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<div id = \"header\">\n");
      out.write("\t\t<div class = \"title\">\n");
      out.write("\t\t\t<h1 class = \"title\">\n");
      out.write("\t\t\t");
 String str = request.getParameter("title"); 
			   if (str == null) {
			       str = "";
			   }
			
      out.write(" \n");
      out.write("\t\t\t");
      out.print(str );
      out.write("</h1>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class = \"right\">\n");
      out.write("\t\t\t<a href = \"login.jsp\">Logout</a>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<hr>\n");
      out.write("\t<div id = \"content\">\n");
      out.write("\t\t<div class = \"left-column\">\n");
      out.write("\t\t\tPortfolios\n");
      out.write("\t\t\t<ul>\n");
      out.write("\t\t\t\t<li><a href = \"portfolio.jsp?title=My Portfolio\">My Portfolio</a>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class = \"main\">\n");
      out.write("\t\t\t<div class = \"form\">\n");
      out.write("\t\t\t\t<form action = \"portfolio.jsp\" name = \"record\" method = \"POST\">\n");
      out.write("\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t<table>\n");
      out.write("\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t<th>Type</th>\n");
      out.write("\t\t\t\t\t\t\t<th>Symbol</th>\n");
      out.write("\t\t\t\t\t\t\t<th>Shares</th>\n");
      out.write("\t\t\t\t\t\t\t<th>Price</th>\n");
      out.write("\t\t\t\t\t\t\t<th>Commission</th>\n");
      out.write("\t\t\t\t\t\t\t<th>Note</th>\n");
      out.write("\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t\t<select>\n");
      out.write("\t\t\t\t\t\t\t\t<option value = \"buy\">Buy</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value = \"sell\">Sell</option>\n");
      out.write("\t\t\t\t\t\t\t\t</select> \n");
      out.write("\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t\t<input type = \"text\" name = \"Symbol\">\n");
      out.write("\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t\t<input type = \"text\" name = \"Shares\">\n");
      out.write("\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t\t<input type = \"text\" name = \"Price\">\n");
      out.write("\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t\t<input type = \"text\" name = \"Commission\">\n");
      out.write("\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t\t<input type = \"text\" name = \"Note\">\n");
      out.write("\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t</table>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class = \"section\">\n");
      out.write("\t\t\t\t\t<input type = \"checkbox\" name = \"isDeduct\">Deduct from cash\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class = \"section\">\n");
      out.write("\t\t\t\t\t<input type = \"submit\" name = \"add_portfolio\" value = \"Add to portfolio\">\n");
      out.write("\t\t\t\t\t<input type = \"submit\" name = \"cancel_portfolio\" value = \"Cancel\">\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t</form>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<hr>\n");
      out.write("\t\t\t<div class = \"form\">\n");
      out.write("\t\t\t\t<form action = \"portfolio.jsp\" name = \"record\" method = \"POST\">\n");
      out.write("\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t<table>\n");
      out.write("\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t<th>Type</th>\n");
      out.write("\t\t\t\t\t\t\t<th>Date</th>\n");
      out.write("\t\t\t\t\t\t\t<th>Amount</th>\n");
      out.write("\t\t\t\t\t\t\t<th>Note</th>\n");
      out.write("\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t\t<select>\n");
      out.write("\t\t\t\t\t\t\t\t<option value = \"Deposit\">Deposit</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value = \"Withdraw\">Withdraw</option>\n");
      out.write("\t\t\t\t\t\t\t\t</select> \n");
      out.write("\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t\t<input type = \"text\" name = \"Date\">\n");
      out.write("\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t\t<input type = \"text\" name = \"Amount\">\n");
      out.write("\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t\t<input type = \"text\" name = \"Note\">\n");
      out.write("\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t</table>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class = \"section\">\n");
      out.write("\t\t\t\t\t<input type = \"submit\" name = \"add_portfolio\" value = \"Add to portfolio\">\n");
      out.write("\t\t\t\t\t<input type = \"submit\" name = \"cancel_portfolio\" value = \"Cancel\">\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t</form>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<hr>\n");
      out.write("\t\t\t<div class = \"form\">\n");
      out.write("\t\t\t\t<form>\n");
      out.write("\t\t\t\t\t<table >\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<th>Name</th>\n");
      out.write("\t\t\t\t\t\t<th>Symbol</th>\n");
      out.write("\t\t\t\t\t\t<th>Last Price</th>\n");
      out.write("\t\t\t\t\t\t<th>Change</th>\n");
      out.write("\t\t\t\t\t\t<th>Shares</th>\n");
      out.write("\t\t\t\t\t\t<th>Cost bias</th>\n");
      out.write("\t\t\t\t\t\t<th>Mkt Value</th>\n");
      out.write("\t\t\t\t\t\t<th>Gain</th>\n");
      out.write("\t\t\t\t\t\t<th>Gain%</th>\n");
      out.write("\t\t\t\t\t\t<th>Daily Gain</th>\n");
      out.write("\t\t\t\t\t\t<th>Overall Return</th>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t</table>\n");
      out.write("\t\t\t</form>\t\t\t\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<div id = \"footer\">\n");
      out.write("\t\t<center>\n");
      out.write("\t\t\t\n");
      out.write("\t\t</center>\n");
      out.write("\t</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
